{
 "title": "ADP Toolchain - Detailed Status",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "alertmanager-node-exporter, grafana-node-exporter ,prometheus-node-exporter, jenkins-node-exporter,  nexus-node-exporter, sonarqube-node-exporter"
   }
  ]
 },
 "panels": [
  { "title": "Current Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "description": "Dashboard for monitoring  the toolstack",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "content": "# ADP Toolchain - Detailed Status\n\nShowing most important node-exporter metrics.",
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Current Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$job",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Host CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"system\" ,job=\"$job\"})"
    }
   ]
  },
  { "title": "Utilization (%)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Host Memory (%)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{job=\"$job\"}) - (node_memory_MemAvailable_bytes{job=\"$job\"}))/ (node_memory_MemTotal_bytes{job=\"$job\"}) * 100 "
    }
   ]
  },
  {
   "title": "Host CPU (%)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(node_cpu_seconds_total{mode=~\"user|nice|system|irq|softirq|steal|idle|iowait\" ,job=\"$job\"}) by (instance, job)) - ( sum(node_cpu_seconds_total{mode=~\"idle|iowait\" ,job=\"$job\"}) by (instance,job) )   )   /  (sum(node_cpu_seconds_total{mode=~\"user|nice|system|irq|softirq|steal|idle|iowait\" ,job=\"$job\"}) by (instance, job)) * 100"
    }
   ]
  },
  {
   "title": "Pod Disk (%)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 *(1 - (node_filesystem_free_bytes{job=\"$job\", mountpoint=\"/\", device=\"rootfs\"}  /node_filesystem_size_bytes{job=\"$job\",  mountpoint=\"/\", device=\"rootfs\"}) )",
     "legendFormat": "root filesystem"
    },
    {
     "expr": "100 *(1 - (node_filesystem_free_bytes{job=\"$job\", mountpoint=\"/prometheus\"}  /node_filesystem_size_bytes{job=\"$job\",  mountpoint=\"/prometheus\"}) )",
     "legendFormat": "prometheus-pvc"
    },
    {
     "expr": "100 *(1 - (node_filesystem_free_bytes{job=\"$job\", mountpoint=\"/nexus-data\"}  /node_filesystem_size_bytes{job=\"$job\",  mountpoint=\"/nexus-data\"}) )",
     "legendFormat": "nexus-pvc"
    },
    {
     "expr": "100 *(1 - (node_filesystem_free_bytes{job=\"$job\", mountpoint=\"/var/lib/jenkins/jobs\"}  /node_filesystem_size_bytes{job=\"$job\",  mountpoint=\"/var/lib/jenkins/jobs\"}) )",
     "legendFormat": "jenkins-persistent-pvc"
    },
    {
     "expr": "100 *(1 - (node_filesystem_free_bytes{job=\"$job\", mountpoint=\"/var/lib/pgsql/data\"}  /node_filesystem_size_bytes{job=\"$job\",  mountpoint=\"/var/lib/pgsql/data\"}) )",
     "legendFormat": "sonarqube-persistent-pvc"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "repeat": "instance",
   "yaxes": [
    { "format": "bits", "label": "bits in (-) / bits out (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"eth0\", job=\"$job\"}[5m])*8",
     "legendFormat": "{{device}}_in"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device=\"eth0\", job=\"$job\"}[5m])*8",
     "legendFormat": "{{device}}_out"
    }
   ]
  }
 ]
}