{
 "title": "ADP Toolchain - Status",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Monitoring Stack", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prometheus",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"prometheus-node-exporter\"}"
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"grafana-node-exporter\"}"
    }
   ]
  },
  {
   "title": "Alert Manager",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"alertmanager-node-exporter\"}"
    }
   ]
  },
  { "title": "Tool Stack", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Jenkins",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"jenkins-node-exporter\"}"
    }
   ]
  },
  {
   "title": "Nexus",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"nexus-node-exporter\"}"
    }
   ]
  },
  {
   "title": "Sonarqube",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"sonarqube-node-exporter\"}"
    }
   ]
  },
  {
   "title": "Status Graph",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "1 -> UP / 0 -> DOWN" }
   ],
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  }
 ]
}